sudo: required
language: python
python:
  - "2.7"

services:
  - docker

install:  
  - sudo pip install python-coveralls

script:
  - docker-compose run test ./bin/test-entrypoint.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ./bin/deploy.sh heroku;
    fi
  - coveralls -d .coverage
