sudo: required

services:
  - docker

install:
  - sudo pip install codecov

script:
  - docker-compose run test ./bin/test-entrypoint.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ./bin/deploy.sh heroku;
    fi
  - codecov
