sudo: required

services:
  - docker

install:
  - npm install apidoc -g
  - apidoc -i beluga/ -o docs

script:
  - docker-compose run test pytest -vvv
    
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    on:
      branch: "chad/#22-push-api-docs"