sudo: required

services:
  - docker

install:
  - sudo npm install apidoc -g
  - sudo apidoc -i beluga/ -o docs

script:
  - docker-compose run test pytest -vvv

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      ./bin/deploy.sh $DEPLOY_TARGET;
    fi
    
deploy:
  provider: gcs
  access_key_id: $GCS_ACCESS_KEY
  secret_access_key: $GCS_ACCESS_SECRET
  bucket: "gs://beluga-docs/api"
  acl: public-read
  local-dir: docs