FROM python:3.6-stretch

# Install production dependencies.
ADD worker/requirements.txt /env/requirements.txt
RUN pip install -r /env/requirements.txt

# Add application to container.
COPY worker/ /app/worker/
COPY beluga/ /app/beluga/

WORKDIR /app/

CMD celery -A worker.celery worker -l INFO -B
